def create_table():
    session = _db()
    create_query = text("""
        CREATE TABLE available_action (
            product_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
            product_name VARCHAR2(255) NOT NULL,
            action_name VARCHAR2(255) NOT NULL,
            status VARCHAR2(20) CHECK (status IN ('open', 'close')) NOT NULL,
            region VARCHAR2(255),
            env VARCHAR2(10) CHECK (env IN ('dev', 'stg', 'prd')),
            updated_at TIMESTAMP DEFAULT SYSDATE,
            updated_by VARCHAR2(255),
            ecosystem VARCHAR2(255),
            block_api VARCHAR2(1) CHECK (block_api IN ('y', 'n')) NOT NULL,
            ecosystem_overrides CLOB,
            
            CONSTRAINT pk_available_action PRIMARY KEY (product_id),
            CONSTRAINT uq_available_action UNIQUE (product_name, action_name, region, env)
        )
    """)
    session.connection().execute(create_query)
    print("✅ Table 'available_action' créée avec succès (avec contrainte d’unicité et CLOB).")
